### ISSUE TITLE
The video player example keeps playing after leaving the screen

### ISSUE THREAD

**Issue by pohuing** [skiptools/skipapp-showcase#4]
Playing the example video under showcase -> Video Player and leaving the screen does not stop the video.
I can't test if this is intentional since I don't have an iPhone but I doubt it is.

Turn on the sound to hear the issue:

https://github.com/user-attachments/assets/9734e17e-f0b9-4269-9a67-3a2df4b60194

This is with up to date showcase installed from Google play on an Asus Zenfone 10 running Android 14.

**Comment by aabewhite** [comment]
Thanks! Submitting a fix today...
